services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
