// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createProduct = `-- name: CreateProduct :one
  INSERT INTO products ("seller_id","product_name","description","base_price","auction_end")
  VALUES($1,$2,$3,$4,$5)
  RETURNING id
`

type CreateProductParams struct {
	SellerID    uuid.UUID       `json:"seller_id"`
	ProductName string          `json:"product_name"`
	Description string          `json:"description"`
	BasePrice   decimal.Decimal `json:"base_price"`
	AuctionEnd  time.Time       `json:"auction_end"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SellerID,
		arg.ProductName,
		arg.Description,
		arg.BasePrice,
		arg.AuctionEnd,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProductById = `-- name: GetProductById :one
 Select id, seller_id,  product_name, description, base_price, auction_end, is_sold, created_at, updated_at
 FROM products
 WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.ProductName,
		&i.Description,
		&i.BasePrice,
		&i.AuctionEnd,
		&i.IsSold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductsNotSold = `-- name: GetProductsNotSold :many
 Select id, auction_end FROM products
 WHERE is_sold = false
`

type GetProductsNotSoldRow struct {
	ID         uuid.UUID `json:"id"`
	AuctionEnd time.Time `json:"auction_end"`
}

func (q *Queries) GetProductsNotSold(ctx context.Context) ([]GetProductsNotSoldRow, error) {
	rows, err := q.db.Query(ctx, getProductsNotSold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsNotSoldRow
	for rows.Next() {
		var i GetProductsNotSoldRow
		if err := rows.Scan(&i.ID, &i.AuctionEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
